### ISSUE TITLE
Anyway to not open Apple Music?

### ISSUE THREAD

**Issue by valentinegb** [DylanCa/apple-music#12]
It seems that every function in this library will launch Apple Music if it isn't already open. Anyway to prevent this? Or at least, anyway to check if Apple Music isn't open?

**Comment by DylanCa** [comment]
As far as I know, since we're using Apple Script under the hood and Apple Script needs the related service running to work properly, we need Apple Music to be opened in order to work. Couldn't find a way to have AM closed and make the lib work unfortunately :(
